{% set version = "1.2.8" %}

package:
  name: zlib
  version: {{ version }}

source:
  fn: zlib-{{ version }}.tar.gz
  url: http://zlib.net/zlib-{{ version }}.tar.gz
  md5: 44d667c142d7cda120332623eab69f40

build:
  number: 4
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - msinttypes  # [win and py<35]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
   commands:
    - test -f ${PREFIX}/lib/libz.a  # [not win]
    #- conda inspect linkages -p $PREFIX zlib  # [not win]
    #- conda inspect objects -p $PREFIX zlib  # [osx]

about:
  home: http://zlib.net/
  license: zlib (http://zlib.net/zlib_license.html)
  summary: 'Massively spiffy yet delicately unobtrusive compression library.'
  license_family: Other
  license_file: license.txt

extra:
  recipe-maintainers:
    - groutr
    - msarahan
    - ocefpaf
