{% set version = "1.2.11" %}

package:
    name: zlib
    version: {{ version }}

source:
    fn: zlib-{{ version }}.tar.gz
    url: http://zlib.net/zlib-{{ version }}.tar.gz
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1

build:
    number: 0
    run_exports:
        - {{ pin_subpackage('zlib', max_pin='x.x.x') }}

requirements:
    build:
        - cmake       # [win]
        - msinttypes  # [win and vc<14]
        - {{ compiler('c') }}  # [win]
        - toolchain   # [unix]

test:
    commands:
        - test -f ${PREFIX}/lib/libz.a              # [unix]
        - test -f ${PREFIX}/lib/libz${SHLIB_EXT}    # [unix]
        - conda inspect linkages -p ${PREFIX} zlib  # [linux]

about:
    home: http://zlib.net/
    # http://zlib.net/zlib_license.html
    license: zlib
    summary: Massively spiffy yet delicately unobtrusive compression library
    license_family: Other
    license_file: license.txt

extra:
    recipe-maintainers:
        - groutr
        - msarahan
        - ocefpaf
