{% set version = "1.2.8" %}

package:
    name: zlib
    version: {{ version }}

source:
    fn: zlib-{{ version }}.tar.gz
    url: http://zlib.net/zlib-{{ version }}.tar.gz
    sha256: 2a0dd0894c35b8736ff2bee925aab35b473a6c6b432b25e56442bacb0e72bc3a

build:
    number: 3
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
    build:
        - python  # [win]
        - cmake  # [win]
        - msinttypes  # [win and py<35]

test:
    commands:
        - test -f ${PREFIX}/lib/libz.a  # [unix]
        - conda inspect linkages -n _test zlib  # [linux]

about:
    home: http://zlib.net/
    license: zlib (http://zlib.net/zlib_license.html)
    summary: Massively spiffy yet delicately unobtrusive compression library
    license_family: Other
    license_file: license.txt

extra:
    recipe-maintainers:
        - groutr
        - msarahan
        - ocefpaf
