{% set version = "1.2.11.1-motley" %}

package:
    name: zlib
    version: {{ version }}

source:
    git_rev: develop
    git_url: https://github.com/madler/zlib.git

build:
    number: 0
    run_exports:
        # mostly OK, but some scary symbol removal.  Let's try for trusting them.
        #    https://abi-laboratory.pro/tracker/timeline/zlib/
        - {{ pin_subpackage('zlib', max_pin='x.x') }}

requirements:
    build:
        - cmake                                 # [win]
        - msinttypes                            # [win and vc<14]
        # compiler on osx depends on zlib itself. Use the bootstrap compiler instead on osx
        - {{ compiler('c') }}
        - make                                  # [unix]

test:
    commands:
        - test -f ${PREFIX}/lib/libz.a  # [unix]

about:
    home: http://zlib.net/
    # http://zlib.net/zlib_license.html
    license: Zlib
    summary: Massively spiffy yet delicately unobtrusive compression library
    license_family: Other
    license_file: license.txt
    
    description: |
      zlib is designed to be a free, general-purpose, lossless data-compression
      library for use on virtually any computer hardware and operating system.
    doc_url: http://zlib.net/manual.html
    dev_url: https://github.com/madler/zlib

extra:
    recipe-maintainers:
        - groutr
        - msarahan
        - ocefpaf
        - mingwandroid
