conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
  win_arm64: win_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
os_version:
  linux_64: alma8
  linux_aarch64: alma8
  linux_ppc64le: alma8
test: native_and_emulated
