provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
azure:
  store_build_artifacts: true
