travis:
  secure:
    BINSTAR_TOKEN: n50b4YE3Wi0RQLpelwlKHCVRTsouhsSYF9Wq8CTtWCaZGVdyckt6Rl9ochJEZbdneI1iH/3o8Q+YdvZ+Pqu/yeahBPReTK2/eqZdinJO5dKbX9XEqEfMzFn6DK/eS/W6iafqIILOHaY/lXdREy+SnVemOYkMxe1mMFD9S/yfPrAvrkiwAIujFu/n7AfZLdbwdZKgdaAYQWtW8U3Uu1aViApCrjcR5Um63c4l07jDPBk+NrEqkwhWQV86G7djqj/O/kJpBE/RYhwyxNWsCtSkBHSiggUXGAKiXYIh1L11y/JpuejKncuSNWzdrhdJG3zqFy1XVGuNOXUPEFrlRcxJoSe9l1WsoH46SH7rJ2u/MxUFpHNA3B6gHuy518Y4aDbxxGk3P9aYeT7EXHQgfeBJOgb/nnN08dass6NZh8VaJOzMqpo8NaMqsr5Cd/s3WFhUIOZ01viD7YT7ftL1QjrmZBk7AHhy1/Bybtct0ZJV2IsAYVhd8QkGm3MAd+FFAMmy1fSkquAFGhrG9kiodI0RvJgOQD8RQ0uuoRyw33Blcm3mfdMrAXno4eWPleO4+zSvtKsMxpN/eWL3+YD/FJMflucjtdlJGWbtqXnQIBU0n4G9sUXGhD/eP7zkG7lJyEngeDuLKTxdn6rCVaYZU2ivJ2G4pkYzVtpew0qwD6KokFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
compiler_stack: comp7
