appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: native}
travis:
  secure: {BINSTAR_TOKEN: jEW4HwQc8nJl5hhcRgY60eRWm98xKiKeJmxqkLQiJ6qcc08c7aY/gwX4X6aHEcsLGVvakuc+4hgandNR7ibYdQQ6yEcLinxnmVsUphlpAJTvKktjR+gUHhkbF6vtbtk6/sfYt72kaZ2NBPds+8/avdRUHKdV0WzRBL5jl1JLvTrZAJeMriRoEEpcKIi6sxbscR+O2sPa7zL6kAgz5kOn9un7PF4SgeIhtM30ly1XD1YtNq7zfvNNXlcqa8mTP+09LY2AmVEKzWEeoiKFpMryPj1dYDIvarc/8qc0wtI0WqjhHmea8fXCzu3txqKQARSllPxxOcyBBvDgv8wT+VcFsF6G6Q7ZEda2A1UqpLxsomLWnIbduwmOqwNKJ1nrePjZIvr7wCHgNkew/3lFrbIwVwMkSSlZu3fnt1hdOk3HxijeuLnFoSpsmKzkVW+wg2f3eMxokKkwt0f7qx3PtT1ekjvxiBl8slLuPL5dnmTgO9FFFAntu0v+FNgPFwiVLBizXLgxDBP7SvgKZNwKad2sj9bmaX6XvrjxjS29GKedFL6GXvP969kxOz3Wz9eqlJqPkND60fwwu0zmcyw5uUmxZH2MFfAjB1hYBlxxMNlcWMQWf0N/H/uSjYwK6uhiFesquTkb7FkNV0Cct4iAONUqKOLYRcok2RdCgzRledJP/6c=}
