# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

name: Build conda package
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.CONFIG }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - CONFIG: linux_64_
            UPLOAD_PACKAGES: True
            DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
            os: ubuntu
          - CONFIG: osx_64_
            UPLOAD_PACKAGES: True
            os: macos
          - CONFIG: osx_arm64_
            UPLOAD_PACKAGES: True
            os: macos
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
      if: matrix.os == 'windows'

    - name: Configure binfmt_misc on Linux
      script: |
        docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
        ls /proc/sys/fs/binfmt_misc/
      condition: !startsWith(matrix.CONFIG, 'linux_64')
      displayName: Configure binfmt_misc

    - name: Build on Linux
      if: matrix.os == "linux"
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        DOCKERIMAGE: ${{ matrix.DOCKERIMAGE }}
        CI: github
      run: |
        env
        ./.scripts/run_docker_build.sh

    - name: Build on macOS
      if: matrix.os == "macos"
      env:
        CONFIG: ${{ matrix.CONFIG }}
        UPLOAD_PACKAGES: ${{ matrix.UPLOAD_PACKAGES }}
        CI: github
      run: |
        env
        ./.scripts/run_osx_build.sh
